### ISSUE TITLE
فعل امری داشته باش

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#12]
در مورد فعل امری داشته باش، برچسب ریر نقش دستوری و نقش وابستگی چه چیزی باید دریافت کنند؟
مقادیر زیر معتبر هستند؟
cpos=V_PRS   (present verb)
depRel=aux

**Comment by rasoolims** [comment]
در فعل‌های امری داشته ریشه است و باش فعل کمکی است

**Comment by rasoolims** [comment]
صرف امری داشتن در فارسی معاصر به این صورت است (داشته باش، باشید، باشیم...)

**Comment by rasoolims** [comment]
وجه امری برای باش/بودن است
ولی ریشه همان فعل اصلی است

**Comment by rasoolims** [comment]
به ویژگی 
tma 
در خود دادگان نگاه کنید و بر اساس آن تصمیم بگیرید
