### ISSUE TITLE
لیست افعال پیشوندی که به غلط جدا نوشته شده اند

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#13]
word_lemma	word_form	sentID	token_ID
فرا#داد#ده	فرا داد	30705	35
بر#‌آشوبید#آشوب	بر می‌آشوبید	30713	4
باز#داشت#دار	باز خواهند داشت	32692	5
بر#بست#بند	بر می‌بندد	47916	31
در#ماند#مان	در خواهیم ماند	39187	15
در#آورد#آور	در خواهد آورد	39734	22
پذیرفت#پذیر	پذیرفته می‌گردند	40176	4
بر#آورد#آور	بر آورند	46967	29
در#آورد#آور	در آوردم	53615	5
باز#گرفت#گیر	باز خواهم گرفت	57461	14
باز#نهاد#نه	باز خواهی نهاد	33305	8
فرا#رسید#رس	فرا خواهد رسید	46360	2
فرو#رفت#رو	فرو رود	36038	21
در#آورد#آور	در خواهند آورد	41765	40

**Comment by rasoolims** [comment]
همان‌طور که قبلاً صحبت کردیم، بهتر است این شکل نادرست در پیکره باقی بماند چون در عمل بسیار بیشتر از این موارد در متن واقعی فارسی دیده می‌شود.

**Comment by phsfr** [comment]
لیست افعال اصلاح شد.
