### ISSUE TITLE
تبدیل نقش ADR

### ISSUE THREAD

**Issue by rasoolims** [phsfr/Persian-Universal-Dependency-Dadegan#20]
برای نقش 
ADR
پیکره اوپسالا نقش
INTJ
را جایگزین کرده، نظر شما چی هست؟
کلمات این نقش:
هی
یا
ا
آهای
ای

_Originally posted by @phsfr in https://github.com/phsfr/Persian-Universal-Dependency-Dadegan/issues/18#issuecomment-594155908_

**Comment by rasoolims** [comment]
به نظر می‌رسد درست باشد
چون در انگلیسی هم کلماتی مانند
Hey
و
Yo
این نقش را گرفته باشند

**Comment by phsfr** [comment]
نقش دستوری 
ADR
با نقش 
INTJ
جایگزین شد.
