### ISSUE TITLE
اصلاح و یک‌دست‌سازی فراموش در سطح پی‌او‌اس

### ISSUE THREAD

**Issue by rasoolims** [phsfr/Persian-Universal-Dependency-Dadegan#22]
http://search.dadegan.ir/advance/W3sibGVtbWEiOiLZgdix2KfZhdmI2LQifV0=

**Comment by rasoolims** [comment]
احتمالاً باید همه را اسم کنیم
https://www.vajehyab.com/?q=%D9%81%D8%B1%D8%A7%D9%85%D9%88%D8%B4&t=like&s=11

**Comment by phsfr** [comment]
نقش دستوری برای تمام وقوع‌های کلمه «فراموش» از
ADJ
به
N
و برای نقش دستوری ریز از
AJP
به
IANM
یکسان‌سازی شد.
