### ISSUE TITLE
نگاشت برچسب نقش دستوری اعداد حروفی با برچسب POSNUM

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#27]
در جملات شماره 
51528, 46857, 40162, 52655, 54678, 43792, 43490, 59164, 59275, 55715, 50679
اعداد حروفی با برچسب
POSNUM
برچسب خورده‌اند مثل: نوروز 98، پیج‌رنک 1، فولاد 330، مادۀ 11و...
این کلمات آیا برچسب
NUM
باید دریافت کنند؟

**Comment by rasoolims** [comment]
بله چون شماره‌اند

**Comment by phsfr** [comment]
این حروف تگ
NUM
دریافت کردند
