### ISSUE TITLE
نگاشت برچسب دستوری برای اعداد ترتیبی چند تکه

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#28]
برای این عبارات مثل هفتۀ بیست و نهم در جمله 43340 تگ دستوری چه چیزی برای هر توکن باید بخورد؟

**Comment by rasoolims** [comment]
The curse of MWEs!
ظاهراً بیست هم معنا و هم نقش وابستهٔ پسین دارد در نتیجه احتمالاً مانند نهم برچسب می‌خورد

**Comment by phsfr** [comment]
تنها فرم نوشتاری به این شکل فقط شامل بیست در اعداد چند تکه بود مثل بیست و یکم، بیست و چهارم .. بنابراین این عدد هم برچسب
adj
دریافت کرد.
