### ISSUE TITLE
نگاشت برچسب دستوری اعداد غیر ترتیبی بصورت نوشتاری

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#29]
برای موارد زیر فکر می‌کنم برچسب 
NUM
باید زده بشود درست است؟
59164 شبکۀ دو
49943 لیگ یک
38214 پایۀ سه
43465 فرمول یک
38253 کلاس چهار

**Comment by rasoolims** [comment]
بله
در این جور موارد ما روساختی عمل می‌کنیم و این وظیفه را به عهدهٔ تجزیه‌گر نحوی می‌گذاریم که مراحل بعدی را انجام دهد.

**Comment by phsfr** [comment]
این موارد به 
NUM
برچسب خوردند.
