### ISSUE TITLE
یکسان سازی ریشه امکانات

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#3]
در داده اصلی، ریشه امکانات برای برخی کلمات امکان و برخی دیگر امکانات خورده است. ریشه درست این کلمه برای یک دست سازی کدام است؟

**Comment by rasoolims** [comment]
بسیاری از واژه‌های وام‌گرفته از عربی در طی زمان تغییر نقش پیدا کرده‌اند. مثلاً امکانات در عمل معنای مفرد می‌دهد و لذا به همین خاطر دچار چندصدایی بین برچسب‌زنان شده‌ایم. پیشنهاد می‌کنم علی‌الحساب همان »امکان« را بگذاریم چون به نظر می‌آید در پیکره بیشتر مورد پسند برچسب‌زنان بوده است.

**Comment by phsfr** [comment]
ریشه تمام وقوع های کلمه «امکانات» به «امکان» یکسان‌سازی شد.
