### ISSUE TITLE
موارد مجهول در نگاشت تگ PRENUM

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#31]
چند در عبارت این چند تا کلمۀ بی‌مصرف در جمله 55397 باید چه نقشی بگیرد؟

**Comment by phsfr** [comment]
نیم در عباراتی مثل نیم ساعت
سه سال و نیم
نیم کیلوگرم چه نقشی دارد؟

**Comment by phsfr** [comment]
یکی در عبارت یکی دو سال چه نقشی دارد؟

**Comment by phsfr** [comment]
در جمله 46471 عبارت آخر عمرش کلمه آخر چه نقشی دارد؟

**Comment by phsfr** [comment]
در جمله 47090 تک نرخی شدن ارز کلمه تک چه نقشی دارد؟

**Comment by phsfr** [comment]
در جمله 31166 برای کلمه نصف در عبارت ساعت 2 نصف شب چطور؟

**Comment by rasoolims** [comment]
> نیم در عباراتی مثل نیم ساعت
> سه سال و نیم
> نیم کیلوگرم چه نقشی دارد؟

به نظرم می‌آید نیم هم شمارشی است و مانند سه نقش می‌گیرد. سه سال و نیم معادل سه و نیم سال است و باید به همان شکل باهاش برخورد شود.

**Comment by rasoolims** [comment]
> چند در عبارت این چند تا کلمۀ بی‌مصرف در جمله 55397 باید چه نقشی بگیرد؟

احتمالاً شبیه به 
few
در انگلیسی صفت می‌شود
The few times I have consulted with a travel agent I was able ...

**Comment by rasoolims** [comment]
> در جمله 31166 برای کلمه نصف در عبارت ساعت 2 نصف شب چطور؟

صفت است شبیه به
half

**Comment by rasoolims** [comment]
> در جمله 47090 تک نرخی شدن ارز کلمه تک چه نقشی دارد؟

البته درستش آن است که تک‌نرخی یک واژه باشد ولی اینجا تک شبیه یک است. پس نقشی شبیه یک در این حالت می‌گیرد که صفت است.

**Comment by rasoolims** [comment]
> در جمله 46471 عبارت آخر عمرش کلمه آخر چه نقشی دارد؟

در این مورد به نظرم در دادگان اشتباه خورده و آخر اسمی است که عمرش اضافه‌اش می‌شود. مانند این جمله در پیکره انگلیسی

# text = When their precious cartoons are released I highly doubt it will look like the end of the world.
1	When	when	ADV	WRB	PronType=Int	6	mark	6:mark	_
2	their	they	PRON	PRP$	Number=Plur|Person=3|Poss=Yes|PronType=Prs	4	nmod:poss	4:nmod:poss	_
3	precious	precious	ADJ	JJ	Degree=Pos	4	amod	4:amod	_
4	cartoons	cartoon	NOUN	NNS	Number=Plur	6	nsubj:pass	6:nsubj:pass	_
5	are	be	AUX	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin	6	aux	6:aux	_
6	released	release	VERB	VBN	Tense=Past|VerbForm=Part	9	advcl	9:advcl:when	_
7	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	9	nsubj	9:nsubj	_
8	highly	highly	ADV	RB	_	9	advmod	9:advmod	_
9	doubt	doubt	VERB	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin	0	root	0:root	_
10	it	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	12	nsubj	12:nsubj	_
11	will	will	AUX	MD	VerbForm=Fin	12	aux	12:aux	_
12	look	look	VERB	VB	VerbForm=Inf	9	ccomp	9:ccomp	_
13	like	like	ADP	IN	_	15	case	15:case	_
14	the	the	DET	DT	Definite=Def|PronType=Art	15	det	15:det	_
15	end	end	NOUN	NN	Number=Sing	12	obl	12:obl:like	_
16	of	of	ADP	IN	_	18	case	18:case	_
17	the	the	DET	DT	Definite=Def|PronType=Art	18	det	18:det	_
18	world	world	NOUN	NN	Number=Sing	15	nmod	15:nmod:of	SpaceAfter=No
19	.	.	PUNCT	.	_	9	punct	9:punct	_

**Comment by phsfr** [comment]
> 46471
برچسب نقش دستوری و نقش وابستگی برای کلمه آخر و عمرش در این جمله اصلاح شد.

**Comment by phsfr** [comment]
به این ترتیب برای این نقش دستوری موارد زیر نقش صفت و باقی موارد شامل اعداد به حروف و رقم و یا موارد مطرح شده در بالا برچسب عدد دریافت کردند:
`['تک','نصف','چند','دهمین','آخرین','یکمین','سی‌امین','هفتمین','بیستمین','سومین','پنجمین','شصتمین','نهمین','دومین','اول','چهاردهمین','چهارمین','اولین','هشتمین','دوازدهمین','ششمین','یازدهمین','نخستین']
`
