### ISSUE TITLE
برچسب POSTP برای کلمه «و» در پیکره 

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#33]
در جمله زیر (جمله شماره 43242) «و» برچسب 
POSTP
گرفته ولی تنها و ای هست که نقش وابستگی
OBJ
دارد. آیا باید برچسب نقش دستوری آن به 
CONJ
اصلاح شود؟
گلی را در باغچه یا گلدان بکارید و به زندگیتان تشبیه بکنید

**Comment by rasoolims** [comment]
در این مورد خاص دلیلش داشتن دو مفعول برای یک فعل بوده است
در پیکرهٔ یونیورسال در سطح نحو باهاش برخورد می‌شود
https://universaldependencies.org/u/overview/complex-syntax.html

در سطح دستوری قاعدتاً برچسب و غلط است و باید مثل بقیهٔ وها باهاش برخورد شود

**Comment by phsfr** [comment]
تگ نقش دستوری برای کلمه و از 
POSTP
به
CONJ/CONJ
اصلاح شد.
