### ISSUE TITLE
نقش دستوری همراه به عنوان POSTP

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#37]
در جمله زیر شماره 45026 همراه نقش 
POSTP
دریافت کرده، درسته؟
اگر شهد باقلوا شکرک زده باشد، هنگام مصرف می‌توان کمی آن را گرم کرد و مجدداً کمی شهد (همراه با آب لیمو ترش) به آن اضافه کرد و سرو نمود.

**Comment by rasoolims** [comment]
اشتباه است و باید پیشین بخورد

**Comment by phsfr** [comment]
تگ کلمه همراه در این جمله از
POSTP
به
PREP
اصلاح شد.
