### ISSUE TITLE
موارد کلمه «در» که برچسب نقش دستوری POSTP دارند

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#39]
در جملات زیر (شماره‌های24268، 44635 و 44090) برچسب «در» به عنوان 
POSTP
خورده، درست است؟ 
امروز هم **در** شرایطی که سایر تیم‌های مدعی ناکام ماندند 
برادر کوچکم را **در** زیر زمین خاک کرده بودند.
غالباً مردم پاکستان ...، برای دلیل محکم **در** گفتار خود، شعر و یا ضرب‌المثل فارسی را شاهد می‌آورند.

**Comment by rasoolims** [comment]
اشتباه است و باید تصحیح به پیشین شود

**Comment by phsfr** [comment]
کلمه در برای جملات بالا از
POSTP
به
PREP
اصلاح شد.
