### ISSUE TITLE
اشکال در تقطیع وندهای واژه‌های مختوم به مصوت بلند

### ISSUE THREAD

**Issue by rasoolims** [phsfr/Persian-Universal-Dependency-Dadegan#4]
مثال

6-7	زیربنایش	_	_	_	_	_	_	_	_
6	زیربنای	زیربنا	N	IANM	attachment=ISO|number=SING|senID=31168	9	SBJ	_	_
7	ش	او	PRON	PRO	Number=Sing|Person=3|PronType=Prs	6	nmod:poss	_	_

به نظرم باید بشود زیربنا +‌یش

**Comment by phsfr** [comment]
«در پیکره سراجی ی قبل ضمیر به اسم نسبت داده شده بود و اساسا «یش، یم, یت» ندارد. به نظر خودم هم «یش مناسب‌تر  است. پس ی در نهایت به نظرتان به ضمیر بچسبد؟
در مورد کلمات مختوم به «ا» هم ی باید به ضمیر متصل بشود؟ مثل شیوایش, امضایش، املایش, صدایش و..

**Comment by rasoolims** [comment]
به نظرم می‌رسد که »ی« عملاً بخشی از پسوند است. لذا فارغ از آن که در آن پیکره اوپسالا چه شده بهتر است آن را به پسوند نسبت بدهیم.

**Comment by phsfr** [comment]
ی بخشی از ضمیر در نظر گرفته شد.
