### ISSUE TITLE
برچسب POSTP برای کلمه «حدود» در پیکره

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#40]
در جملات شماره 44061، 44135، 58488، 59334، 59474 کلمه «حدود» برچسب 
POSTP
خورده. آیا غلط است؟
بعضی از مخروط‌داران برگ سوزنی کاج امروزی از دانه‌هایی به وجود آمده‌اند که **حدود** پنج هزار سال پیش جوانه زده‌اند.
می‌توان گفت **حدود** 60 سال پیش از میلاد، چهار صورت فلکی در آسمان شکل گرفته بودند
مسجد مشرف به فلکهٔ معلم... احداث گردیده و صحن اصلی مسجد **حدود** 450 متر مربع بوده ...
در مجموع به طور متوسط **حدود** 80 درصد بودجهٔ دانشگاه‌ها تخصیص پیدا کرده است.
او تقریباً **حدود** هشتاد سال بعد از سید رضی به این کار اقدام ورزیده است

**Comment by rasoolims** [comment]
بله 
باید اسم باشند

**Comment by phsfr** [comment]
برخی از وقوع‌های این کلمه برچسب قید و برخی هم حرف اضافه پیشین دارند.
در تمام موارد بالا باید به اسم اصلاح شوند؟

**Comment by rasoolims** [comment]
بله در این مورد نیز نیاز به یکسان‌سازی و اصلاح پیکرهٔ دادگان داریم
از آنجایی که در پیکرهٔ اوپسالا هم اسم خورده قاعدتاً اسم ارجحیت دارد

**Comment by phsfr** [comment]
تمام وقوع‌های حدود یکسان‌سازی شد به
N
