### ISSUE TITLE
برچسب POSTP برای کلمه «جلوی» در پیکره

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#42]
در جمله شماره 58786 کلمه «جلوی» برچسب
POSTP
خورده، باید به چه برچسبی تغییر کند؟
مثل این دست‌فروش‌ها که **جلوی** مغازهٔ دیگران بساط پهن می‌کنند، جلوی سینمای زندگی بساط زده‌اند.

**Comment by rasoolims** [comment]
حرف اضافهٔ پیشین

**Comment by rasoolims** [comment]
البته در پیکره دادگان اینجا هم دوصدایی موجود است. در بخش یادگیری ۴۵ مورد حرف اضافه پیشین و ۲۷ مورد اسم لحاظ شده است.
همه را حرف اضافه پیشین بزنیم بهتر است

**Comment by phsfr** [comment]
برچسب 
POSTP
درباره جمله بالا به
PREP
اصلاح شد و تمام وقوع‌های «جلوی» هم به
PREP
یکدست‌سازی شدند.
فقط برای کلمه «جلو» هیچ تغییری انجام نشد و «جلوی» تغییر پیدا کرد
