### ISSUE TITLE
برچسب POSTP برای کلمه «پیش» در پیکره

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#43]
در جمله شماره 59074 کلمه «پیش» برچسب
POSTP
خورده، باید به چه برچسبی تغییر کند؟
سپیده خانم حسابی غریبی می‌کرد و **پیش** هیچ کس نمی‌رفت.

**Comment by rasoolims** [comment]
حرف اضافه پیشین
#تصحیح پیکره

**Comment by phsfr** [comment]
برچسب پیش از 
POSTP
به
PREP
اصلاح شد.
