### ISSUE TITLE
یکسان‌سازی نقش دستوری جلوی کنار و کناره

### ISSUE THREAD

**Issue by rasoolims** [phsfr/Persian-Universal-Dependency-Dadegan#44]
در پیکره دادگان چندصدایی در این زمینه وجود دارد
با توجه به این که در یونیورسال به صورت حرف اضافه خورده‌اند
فقط آن‌هایی که نقش حرف اضافه‌ای می توانند بپذیرند تبدیل به حرف اضافه پیشین شوند

**Comment by rasoolims** [comment]
اسم می‌شود

**Comment by phsfr** [comment]
تمام وقوع‌های کلمه کنار به
N / IANM
یکسان‌سازی شد.
