### ISSUE TITLE
برچسب نقش دستوری برای کلمات عددی مثل میلیاردها، میلیون‌‌ها، ده‌ها و صدها

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#45]
برای موارد عددی زیر که در پیکره دادگان برچسب
PREM
خورده‌اند و در پیکره اوپسالا برچسب
DET
ندارند چه برچسبی مناسب هست به نظرتان؟
میلیاردها | میلیون‌ها | صدها | ده‌ها
**میلیاردها** تن پودر و گرد نمک در سراسر منطقهٔ غرب و شمال غربی کشور پراکنده خواهد شد.
افراد مرفه و ثروتمند **میلیاردها** دلار از دارایی و ثروت مردم را به جیب زده
این در حالی است که شرکت‌های انگلیسی در نتیجهٔ فروش این تجهیزات ضعیف **میلیون‌ها** پوند به جیب زده‌اند.
آثاری داریم که هر برگش **میلیون‌ها** دلار می‌ارزد
منجر به کشته و زخمی شدن **صدها** تن از عراقی‌ها می‌شود، تبرئه کرد.
به چنین دمکراسی، **ده‌ها** اشکال دینی، منطقی، اخلاقی وارد است.
در پیکره اوپسالا مشابه آن در جمله زیر عدد در نظر گرفته شده:
  ولی ۱۰ درصد به بالا تا ۵۰ درصد را آن هم در **صدها** صندوق نمی‌توان حمل بر اشتباه کرد.

**Comment by rasoolims** [comment]
همزمان دو نظر متناقض دارم که شاید بهتر باشد به نظر اول که تطبیق با زبان انگلیسی دارد عمل نماییم
نظر شما چیست؟

* بر اساس پیکرهٔ انگلیسی
به نظرم می‌رسد این‌ها جمع بسته شده‌اند و رفتار اسمی پیدا کرده‌اند. مثلاً در انگلیسی داریم:
I had been a patient of Dr. Olbina for 9 years and had spent thousands of dollars on crowns etc.
15	thousands	thousand	NOUN	NNS	Number=Plur	14	obj	14:obj	_

دقت کنید که در رابطهٔ وابستگی هم این کلمات ریشه شده‌اند و باید یادمان باشد مثلاً میلیون‌ها دلار، دلار وابسته می شود و میلیون ها هسته

در مجموع پیشنهاد من این است که برای حالاتی که ترجمهٔ مستقیم به انگلیسی وجود دارد، رجوع به ساختار انگلیسی کنیم. همین نمونهٔ صدها که مثال زدید در پیکرهٔ اوپسالا در یک جا عدد خورده است که انسجام با بقیهٔ مواردی که شما پیدا کردید ندارد.

* بر اساس شم زبانی
با وجود جمع بسته شدن این عددها این‌ها هنوز معنای عددی دارند و شماره هستند و 
num
می‌شوند

**Comment by rasoolims** [comment]
دست به رابطهٔ وابستگی نمی‌زنیم ولی برچسب دستوری همهٔ اسم می‌شود

**Comment by phsfr** [comment]
تمام وقوع‌های کلمات میلیاردها، میلیون‌ها، صدها و ده‌ها از 
PREM
به
N/ IANM
یکسان‌سازی و اصلاح شد.
