### ISSUE TITLE
برچسب نقش دستوری کلمه سال‌ها

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#46]
فقط دو مورد در پیکره داریم و بقیه برچسب اسم خورده‌اند. باید اسم بشوند؟
جمله شماره 36548
**سال‌ها** قبل وقتی که به مهاجرت سوئد تن دادیم، برایمان کلاس‌های زبان گذاشتند.
جمله شماره 56445
درد **سال‌ها** هجرت و مظلومیت را با وعدهٔ آمدن تو التیام می‌دهیم.

**Comment by rasoolims** [comment]
این مثال مرا مجاب می‌کند که نظر اول را قبول کنم
#45

**Comment by phsfr** [comment]
تمام وقوع‌های کلمه سال‌ها از
PREM
به
N/ IANM
یکسان‌سازی و اصلاح شد.
