### ISSUE TITLE
برچسب نقش دستوری کلمه ساعتها

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#47]
فقط این یک مورد در جمله شماره 24039 وجود داشت:
**ساعتها** کار کارشناسی بر روی نمونه‌های کالایی از طرف کارشناسان انجام شده و هزاران قلم کالا نمونه‌برداری شده و با موارد عرضه‌شده در نمایشگاه تطابق داده شده است.
در این جمله برچسب
PREM
خورده
در اوپسالا اسم خورده:
تمام خصوصیات مثبت یک انسان والا در او جمع بود؛ که من حالا بخشی از خصوصیات اخلاقی آن بزرگوار را خیلی مختصر عرض می‌کنم؛ اما واقعاً **ساعتها** وقت لازم است که انسان دربارهٔ خصوصیات اخلاقی پیامبر حرف بزند.

**Comment by rasoolims** [comment]
این مثال مرا مجاب می‌کند که نظر اول را قبول کنم
https://github.com/phsfr/Persian-Universal-Dependency-Dadegan/issues/45

**Comment by phsfr** [comment]
تمام وقوع‌های کلمه ساعتها از 
PREM
به
N/ IANM
یکسان‌سازی و اصلاح شد.
