### ISSUE TITLE
نگاشت نقش دستوری «لحظه‌ای» در پیکره

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#49]
این کلمه باید به چه تگی اصلاح شود؟
تگ فعلی:
PREM
اوقاتی را به خاطر دارم که آقای فرهمند با پیکان سورمه‌ای‌رنگ دوکلاجه‌اش به تعلیم پدر همت گماشته بود اما دریغ از **لحظه‌ای** رضایت در نگاه مربی.
جمله شماره: 32327

**Comment by rasoolims** [comment]
اسم

**Comment by phsfr** [comment]
این کلمه از 
PREM
به
N/IANM
اصلاح شد.
