### ISSUE TITLE
بررسی افعال اسنادی در فارسی

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#55]
بررسی افعال اسنادی که فاعل آنها افتاده است و مسند آنها اسم است.

**Comment by rasoolims** [comment]
@moloodi

**Comment by moloodi** [comment]
لطفا مثالی بزنید. منظور از فاعل آنها افتاده است را متوجه نمی‌شوم.

**Comment by rasoolims** [comment]
طبق تعریف دستورنامهٔ جهانی یک حالت از افعال کمکی هستند که حالت وجودی دارند (یعنی معنای هستن به معنای وجود داشتن) می‌دهند و نباید آن را کاپیولا در نظر گرفت
https://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses

there ‌is food in the kitchen -> is = exists

**Comment by rasoolims** [comment]
البته اگر بخواهیم ترجمه کنیم به فارسی شکل جمله کاملاً تغییر می‌کند

غذا در آشپزخانه است
که غذا نهاد و در مسند می‌شود.

به نظر شما راهی برای یافتن این حالات در زبان فارسی وجود دارد؟

**Comment by moloodi** [comment]
> طبق تعریف دستورنامهٔ جهانی یک حالت از افعال کمکی هستند که حالت وجودی دارند (یعنی معنای هستن به معنای وجود داشتن) می‌دهند و نباید آن را کاپیولا در نظر گرفت
> https://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses
> 
> there ‌is food in the kitchen -> is = exists

اینجا چون اکسپلتیو وجود دارد، فعل کمکی را کاپیولا در نظر نگرفته و در مثال 
she is in the kitchen
فعل ربطی کاپیولا شده است. پس ارتباطی به وجودی یا غیروجودی بودن ندارد.

**Comment by rasoolims** [comment]
آیا برای فارسی مصداقی وجود دارد که فعل اسنادی باشد ولی کاپیولا نشود؟

**Comment by moloodi** [comment]
در مورد وجود یا عدم وجود پوچ‌واژه در زبان فارسی دو عقیدۀ مختلف وجود دارد. عده‌ای مثل درزی به وجود آن قائل هستند و عده‌ای مثل سیمین کریمی آن را در فارسی به رسمیت نمی‌شناسند. من با نظر کریمی موافقم به دلایل زبان‌شناختی متعددی که جای مطرح کردن آن اینجا نیست.
بنابراین تا جایی که من جمله‌ها را دیده‌ام فعل اسنادی ما همواره کاپیولا است.

**Comment by rasoolims** [comment]
@phsfr 
با این وجود لطفاً اصلاح کامل نقش فعل‌های کمکی را اجرا کنید

**Comment by rasoolims** [comment]
> در مورد وجود یا عدم وجود پوچ‌واژه در زبان فارسی دو عقیدۀ مختلف وجود دارد. عده‌ای مثل درزی به وجود آن قائل هستند و عده‌ای مثل سیمین کریمی آن را در فارسی به رسمیت نمی‌شناسند. من با نظر کریمی موافقم به دلایل زبان‌شناختی متعددی که جای مطرح کردن آن اینجا نیست.
> بنابراین تا جایی که من جمله‌ها را دیده‌ام فعل اسنادی ما همواره کاپیولا است.

با این وجود خیلی خوب است که ان‌شاءالله در مقاله به آن اشاره شود.
#58

**Comment by moloodi** [comment]
> > در مورد وجود یا عدم وجود پوچ‌واژه در زبان فارسی دو عقیدۀ مختلف وجود دارد. عده‌ای مثل درزی به وجود آن قائل هستند و عده‌ای مثل سیمین کریمی آن را در فارسی به رسمیت نمی‌شناسند. من با نظر کریمی موافقم به دلایل زبان‌شناختی متعددی که جای مطرح کردن آن اینجا نیست.
> > بنابراین تا جایی که من جمله‌ها را دیده‌ام فعل اسنادی ما همواره کاپیولا است.
> 
> با این وجود خیلی خوب است که ان‌شاءالله در مقاله به آن اشاره شود.
> #58

بله می‌توان در مقاله به آن اشاره نمود؛ اما بحث‌های مفصل زبان‌شناختی دارد که بعید می‌دانم لازم باشد انجام شود.

**Comment by rasoolims** [comment]
> > > در مورد وجود یا عدم وجود پوچ‌واژه در زبان فارسی دو عقیدۀ مختلف وجود دارد. عده‌ای مثل درزی به وجود آن قائل هستند و عده‌ای مثل سیمین کریمی آن را در فارسی به رسمیت نمی‌شناسند. من با نظر کریمی موافقم به دلایل زبان‌شناختی متعددی که جای مطرح کردن آن اینجا نیست.
> > > بنابراین تا جایی که من جمله‌ها را دیده‌ام فعل اسنادی ما همواره کاپیولا است.
> > 
> > 
> > با این وجود خیلی خوب است که ان‌شاءالله در مقاله به آن اشاره شود.
> > #58
> 
> بله می‌توان در مقاله به آن اشاره نمود؛ اما بحث‌های مفصل زبان‌شناختی دارد که بعید می‌دانم لازم باشد انجام شود.

العاقل (= داور مقاله)‌ یکفیه الاشاره

**Comment by moloodi** [comment]
بله درست است.

**Comment by moloodi** [comment]
یک نکته و آن هم اینکه در مورد فعل‌های اسنادی دیگر به‌جز استن و بودن، مثل شدن یا گشتن یا گردیدنهم باید تصمیمی اتخاذ نمود. در پیکرۀ انگلیسی فعل 
become
فعل اصلی جمله در نظر گرفته شده است و برچسب
cop
نگرفته است.

**Comment by moloodi** [comment]
اما شدن‌های ربطی فارسی قاعدتا باید 
cop
در نظر گرفته شوند
هر چند می‌توان در مورد آن بحث هم کرد. آقای رسولی نظرتان چیست @rasoolims
