### ISSUE TITLE
افعال با ریشه چند تکه

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#7]
افعالی در پیکره وجو دارند که ریشه آنها حرف اضافه دارد. جداسازی آنها و نقش وابستگی که هر جزء دریافت می‌کند چطور باید باشد
ریشه	فرم نوشتاری
بر#‌آشوبید#آشوب	بر می‌آشوبید	
باز#آمد#آ	بازخواهی آمد
فرو#دوخت#دوز	فروخواهند دوخت
فرو#رفت#رو	فروخواهد رفت
فرو#کرد#کن	 فرومی‌کند
بر#انگیخت#انگیز	برخواهند انگیخت
بر#آمد#آ	برنخواهند آمد
فرو#کشید#کش	فروخواهد کشید
فرا#گرفت#گیر	فراخواهند گرفت
باز#زد#زن	بازخواهد زد
باز#گرداند#گردان	بازگردانده شد
بر#گزید#گزین	برخواهند گزید
فرو#رفت#رو	فروخواهیم رفت
در#داد#ده	درخواهید داد
بر#گذشت#گذر	برخواهید گذشت
فرو#رفت#رو	فرو رود
باز#آمد#آ	بازخواهم آمد
بر#کشید#کش	برخواهیم کشید
بر#خاست#خیز	برخواهم خاست
بر#گرفت#گیر	برخواهیم گرفت
فرو#کرد#کن	فروخواهند کرد
بر#کرد#کن	برخواهم کرد
وا#گذاشت#گذار	واخواهیم گذاشت
در#ماند#مان	در خواهیم ماند
فرو#نشانید#نشان	فروخواهد نشانید
باز#گرفت#گیر	بازخواهم گرفت
باز#فرستاد#فرست	بازخواهند فرستاد
در#آورد#آور	درخواهند آورد
بر#آورد#آور	برخواهند آورد
بر#بست#بند	بر می‌بندد
در#داد#ده	درخواهند داد
بر#انداخت#انداز	برخواهی انداخت
بر#افتاد#افت	برخواهند افتاد
گفت#گو	 بگویی
بر#دمید#دم	برخواهند دمید
در#آمد#آ	درخواهند آمد
در#کرد#کن	درخواهیم کرد
وا#ماند#مان	واخواهد ماند
در#آورد#آور	درخواهد آورد
در#آورد#آور	در خواهد آورد
کرد#کن	نخواهم کرد
بارید#بار	نباریده بود
پرورد#پرور	پرورده باشد
گرفت#گیر	گرفته بودیم
گفت#گو	گفته باشد
رسید#رس	خواهید رسید
آورد#آور	آورده بودم
چپاند#چپان	چپانده می‌شود
توانست#توان	توانسته بود
داد#ده	داده بودیم
سنجید#سنج	خواهیم سنجید
آمد#آ	نیامده بود
باز#گشت#گرد	بازخواهیم گشت
فرمود#فرما	فرموده باشد
پراکند#پراکن	پراکنده خواهد شد
بر#خورد#خور	برخورده بودند
ورزید#ورز	ورزیده باشد
بر#آشفت#آشوب	برآشفته بود
نامید#نام	نامیده می‌شدند
بر#گشت#گرد	برخواهد گشت
افتاد#افت	خواهی افتاد
ریخت#ریز	ریخته شده
وا#نهاد#نه	واخواهیم نهاد
باز#گشت#گرد	بازخواهم گشت
باز#داشت#دار	باز خواهند داشت
گردانید#گردان	گردانیده است
داد#ده	داده باشید
گفت#گو	گفته باشند
ورزید#ورز	ورزیده بودم
سوخت#سوز	سوخته بودند
سپرد#سپر	سپرده شده است
جوشید#جوش	جوشیده باشد
بوسید#بوس	خواهم بوسید
نشست#نشین	خواهد نشست
بوسید#بوس	بوسیده بودم
فرو#ماند#مان	فروخواهد ماند
فرو#ریخت#ریز	فروخواهد ریخت
باز#نمایاند#نمایان	بازخواهد نمایاند
کرد#کن	نخواهیم شد
گذارد#گذار	خواهیم گذارد
آموخت#آموز	آموخته بودند
گذاشت#گذار	گذاشته بودند
داد#ده	خواهی داد
انداخت#انداز	خواهیم انداخت
خورد#خور	خورده باشند
ترکاند#ترکان	ترکانده است
گذراند#گذران	گذرانده بودم
گذارد#گذار	گذارده است
گسترد#گستر	گسترده بودم
خزید#خز	خزیده بودیم
شنید#شنو	شنیده شده
#است	 است
آورد#آور	آورده شده
بود#باش	خواهم بود
جهاند#جهان	جهانده است
آمد#آ	آمده باشند
باز#گرفت#گیر	باز خواهم گرفت
داشت#دار	نداشته باشند
نگاشت#نگار	نگاشته بودی
فرو#کوفت#کوب	فروخواهد کوفت
فرا#داد#ده	فراخواهیم داد
فرو#نهاد#نه	فروخواهند نهاد
کند#کن	کنده است
افتاد#افت	خواهیم افتاد
گردید#گرد	گردیده باشند
فرو#کشید#کش	فروکشیده می‌شود
گرفت#گیر	گرفته بودم
کرد#کن	 شده است
ورزید#ورز	خواهد ورزید
داشت#دار	نخواهیم داشت
آورد#آور	آورده باشم
فرو#کوبید#کوب	فروخواهد کوبید
چرخید#چرخ	چرخیده بودند
زایید#زا	خواهی زایید
فرا#داد#ده	فرا داد
بست#بند	خواهم بست
گذاشت#گذار	خواهید گذاشت
لغزید#لغز	خواهد لغزید
چشید#چش	چشیده می‌شود
در#آمد#آ	درخواهد آمد
بر#کرد#کن	برخواهید شد
زد#زن	زده باشم
سرود#سرا	خواهی سرود
بالید#بال	بالیده باشم
بر#گردید#گرد	برنخواهد گردید
در#آورد#آور	در خواهند آورد
فرا#گرفت#گیر	فراگرفته باشم
در#انداخت#انداز	درانداخته باشم
زد#زن	زده خواهد شد
داد#ده	خواهم داد
بر#گزید#گزین	برگزیده بودیم
شناخت#شناس	شناخته شد
خواست#خواه	نخواسته است
کشت#کش	خواهد کشت
دید#بین	دیده نشده است
شست#شوی	شسته بودیم
انداخت#انداز	خواهی انداخت
در#آورد#آور	درآورده شد
ماند#مان	خواهد ماند
بر#آورد#آور	بر آورند
بر#آمد#آ	برخواهد آمد
پاشید#پاش	پاشیده شده
کوبید#کوب	کوبیده بشود
هراسید#هراس	هراسیده بودیم
شکفت#شکف	شکفته است
غلطانید#غلطان	غلطانیده شده است
دوید#دو	خواهم دوید
بارید#بار	باریده می‌شود
ور#افتاد#افت	ورافتاده است
خواند#خوان	خواهیم خواند
خوابید#خواب	خوابیده بود
ریخت#ریز	ریخته شد
دوخت#دوز	خواهم دوخت
شکست#شکن	شکسته است
باز#ماند#مان	بازمانده است
در#گذشت#گذر	درگذشته است
فرا#رسید#رس	فرارسیده است
باز#جست#جو	بازجسته است
فرا#گرفت#گیر	فرانگرفته بود
بر#انگیخت#انگیز	برانگیخته شد
گذاشت#گذار	نگذاشته بود
بر#گردانید#گردان	برگردانیده می‌شود
کرد#کن	خواهد شد
در#آورد#آور	در آوردم
بر#گماشت#گمار	برخواهم گماشت
باز#گرفت#گیر	بازخواهند گرفت
افتاد#افت	افتاده بودیم
پذیرفت#پذیر	پذیرفته شدند
تاخت#تاز	خواهند تاخت
فرا#رسید#رس	فرا خواهد رسید
شکافت#شکاف	شکافته است
گذراند#گذران	گذرانده است
شورید#شور	می‌شوریده است
در#داد#ده	درداده باشند
در#آورد#آور	درآورده بود
در#یافت#یاب	درخواهی یافت
باز#نهاد#نه	باز خواهی نهاد
در#نوردید#نورد	درخواهم نوردید
افتاد#افت	افتاده بودند
گذراند#گذران	خواهی گذراند
پسندید#پسند	پسندیده شدند
باز#گشت#گرد	بازخواهد گشت
گرفت#گیر	نخواهم گرفت
خیساند#خیسان	خیسانده می‌شوند
بر#گزید#گزین	برخواهم گزید
کاست#کاه	کاسته نشود
شست#شوی	خواهند شست
بر#زد#زن	برخواهد زد
بر#افراشت#افراز	برخواهد افراشت
خواست#خواه	خواسته باشم
نکوهید#نکوه	کاشته شود
فروخت#فروش	خواهد فروخت
نکوهید#نکوه	نکوهیده بودید
کاست#کاه	کاسته است
فرو#نشانید#نشان	فرونشانیده شد
نشست#نشین	نشسته بودم
رسانید#رسان	خواهد رسانید
زایید#زا	زاییده شده بود
گنجید#گنج	گنجیده باشد
زد#زن	نزده باشم
بر#گردید#گرد	برخواهی گردید
فرو#گرفت#گیر	فروخواهد گرفت
فرا#گرفت#گیر	فراخواهیم گرفت
بر#چید#چین	برخواهد چید
رسید#رس	نمی رسد
مالید#مال	خواهم مالید
شکفت#شکف	شکفته بود
افتاد#افت	نیافتاده بود
گشت#گرد	گشته است
بر#داشت#دار	برداشته بود
ترسید#ترس	ترسیده بودیم
در#داد#ده	درخواهیم داد

**Comment by rasoolims** [comment]
اینها حرف اضافه نیستند و پیشوند فعلی مخصوص فعل‌های پیشوندی‌اند که علی‌القاعده به فعل چسبیده‌اند و نیازی به جداسازی ندارند. 

البته بسیاری از مثال‌های اینجا که آوردید این‌گونه نیستند


در مجموع چند رده فعل در فارسی داریم
ساده مانند دادن
ساده پیشوندی مانند وادادن
مرکب مانند انجام دادن
مرکب پیشوندی 
و اگر اشتباه نکنم فعل حرف اضافه‌ای هم وجود دارد ولی الان خاطرم نیست

**Comment by rasoolims** [comment]
حرف اضافه‌ای مانند
http://search.dadegan.ir/?q=%D8%A7%D8%B2+%D8%A2%D8%A8+%D8%AF%D8%B1%D8%A2%D9%85%D8%AF%D9%86

**Comment by phsfr** [comment]
منظورم از جداسازی این هست که فرم نوشتاری در ستون دوم عینا در پیکره آمده و اینها افعالی هستند که باید تقطیع شوند . الان تقطیع مثلا فراخواهد+گرفت آیا درست است؟ بر اساس شکل نوشتاری فعلی و فاصله ایجاد شده در حال حاضر به این شکل باید تقطیع شود. اگر درست نیست شکل و الگوی درست جداسازی این فرم افعال چگونه است؟

**Comment by rasoolims** [comment]
برای فعل‌های پیشوندی صرف‌شده قسمت اول باید همان‌طوری که بود باشد

مثلاً
```
فراگرفته خواهد شد 
```
تبدیل می‌شود به
```
فراگرفته
خواهد
شد
```

**Comment by phsfr** [comment]
در مواردی که فعل کمکی در وسط قرار گرفته چطور؟
برخواهم گزید
`برخواهم `
`گزید`
؟؟

**Comment by rasoolims** [comment]
بله. پیشوند چسبیده و بی‌نیاز از تقطیع است. این پیشوندها به تنهایی معنایی ندارند.

**Comment by phsfr** [comment]
حالا آیا ریشه ها به صورت زیر برچسب بخورند درست است:
`برخواهم                  خواست#خواه`
`گزید                  بر#گزید#گزین`

**Comment by rasoolims** [comment]
ما اینجا سعی می‌کنیم کاملاً روساختی تحلیل کنیم یعنی
```
بر#خواست#خواه
گزید#گزین
```

**Comment by phsfr** [comment]
این افعال چند تکه به فرم روساختی تقطیع شدند.
