### ISSUE TITLE
شماره جمله

### ISSUE THREAD

**Issue by phsfr** [phsfr/Persian-Universal-Dependency-Dadegan#8]
آیا شماره جمله،  همان شماره جمله در ستون ویژگی و دراصل شماره اصلی جمله باشد یا از 1 شروع شود؟

**Comment by rasoolims** [comment]
شماره تطبیق با شمارهٔ سیکوئل سرور دارد و لزوماً ترتیبی ندارد به جز منحصر به فرد بودن

**Comment by phsfr** [comment]
آیا این شماره در ستون ویژگی حفظ شود؟

**Comment by rasoolims** [comment]
بله، برای تطبیق به عقب از نظر نسخه‌ای نیاز داریم

**Comment by phsfr** [comment]
شماره جمله بصورت ترتیبی تولید و شماره قبلی در ستون ویژگی‌ها نیز حفظ شد.
