### ISSUE TITLE
cop error for "شدن"

### ISSUE THREAD

**Issue by moloodi** [phsfr/Persian-Universal-Dependency-Dadegan#89]
قرار بود "شد" که فعل اصلی جمله می‌شود ریشه به حساب آید مثلا "او تنها شد". بعد مسند بشود اکس‌کامپ. در صورتیکه "شد" شده است کاپ و مسند هم روت.
خطای مهلکی است. حتما اصلاح شود

**Comment by moloodi** [comment]
Sid: 23472 and 23687 just as examples

**Comment by rasoolims** [comment]
https://github.com/phsfr/Persian-Universal-Dependency-Dadegan/commit/698632649a63c627111d5869ec909a0c43a1e04d

**Comment by rasoolims** [comment]
https://github.com/phsfr/Persian-Universal-Dependency-Dadegan/commit/0bc47bd3e5da00e5ce875bbed09cde78b90bc369

**Comment by rasoolims** [comment]
لطفاً مجدد مرور کنید . اگر ایرادی وارد نبود
close issue

**Comment by rasoolims** [comment]
@phsfr 
جهت اطلاع
