### ISSUE TITLE
nsubj error in UD Dadegan

### ISSUE THREAD

**Issue by moloodi** [phsfr/Persian-Universal-Dependency-Dadegan#91]
Fatal and seemingly systematic error:
Sid: 23472
Word: جهان
the word which is the sentence subject has erroneously changed to "flat:name". its correct label: nsubj

**Comment by rasoolims** [comment]
این خطای اساسی  ناشی از مدیریت اشتباه اسم‌های خاص بود

تغییر اخیر این مسأله را مدیریت کرده است اما ما آگاهیم که بسیاری از موجودیت‌های خاص به خاطر خودکار بودن غلط هستند
https://github.com/phsfr/Persian-Universal-Dependency-Dadegan/commit/15198b333be4c1335e0ea309fcc5b51452711395

من تنها بخشی از آن‌ها را اتفاقی پیدا کرده و اعلام کرده‌ام

@phsfr
