### ISSUE TITLE
fatal error in vocative label

### ISSUE THREAD

**Issue by moloodi** [phsfr/Persian-Universal-Dependency-Dadegan#92]
Senid: 41391, 41370, 41340 as some examples
most of the "vocative" labels are not correct. it is not obvious why Mosnad has been changed to vocative. the most frequent type of error in this regard is Mosnad > vocative

**Comment by rasoolims** [comment]
باگ به خاطر در نظر نگرفتن حالت خاص و عمومیت بخشیدن به همهٔ‌ نقش‌ها بود
https://github.com/phsfr/Persian-Universal-Dependency-Dadegan/commit/5dc3fde313bccace7c205bb01b68495a55a89e0d
@phsfr
